title: Positive +
description: >-
  Staying positive during down times. How to remain on track with routines by
  managing free-time.
template:
  repo: positive-+-template
  name: positive-+
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
